=== ruizhang2015/codekp/ASMAnalysisFactory/AutomachineSpecs/automachine.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://mass.pku.edu.cn" 
xmlns:tns="http://mass.pku.edu.cn"  elementFormDefault="qualified">

    

    <element name="Automachine">
    	<complexType>
    		<sequence>
    			<element name="description" type="string" maxOccurs="1" minOccurs="1" />
    			<element name="errorMessage" type="string" maxOccurs="1" minOccurs="1" />
    			<element name="endMeanViolateDefect" type="boolean" maxOccurs="1" minOccurs="1"></element>
    			<element name="severeLevel" type="int" maxOccurs="1" minOccurs="1"></element>
    			<element ref="tns:state" maxOccurs="unbounded" minOccurs="1"/>
    		</sequence>
    	</complexType>
    </element>
  
  <element name="state">
    	<complexType>
   			<sequence>
				<element name="number" type="int" maxOccurs="1" minOccurs="1"></element>
		   		<element name="isEndState" type="boolean" maxOccurs="1" minOccurs="1"></element>
		   		<element name="isOriginState" type="boolean" maxOccurs="1" minOccurs="1"></element>
                <element name="exceptionState" type="int" maxOccurs="1" minOccurs="1"></element>
                <element ref="tns:edge" maxOccurs="unbounded" minOccurs="0"></element>

			 </sequence>
   		</complexType>
   </element>
   
 
   <element name="edge">
   		<complexType>
   			<sequence>
   				<element name="class" type="tns:edgeType" maxOccurs="1" minOccurs="1"></element>
   				<element name="toState" type="int" maxOccurs="1" minOccurs="1"></element>
   				<element name="opcode" type="string" maxOccurs="1" minOccurs="0"></element>
   				<element name="operand" type="int" maxOccurs="1" minOccurs="0"></element>
   				<element name="var" type="int" maxOccurs="1" minOccurs="0"></element>
   				<element name="index" type="int" maxOccurs="1" minOccurs="0"></element>
   				<element name="increment" type="int" maxOccurs="1" minOccurs="0"></element>
   				<element name="dims" type="int" maxOccurs="1" minOccurs="0"></element>
   				<element name="min" type="int" maxOccurs="1" minOccurs="0"></element>
   				<element name="max" type="int" maxOccurs="1" minOccurs="0"></element>
   				<element name="owner" type="string" maxOccurs="1" minOccurs="0"></element>
   				<element name="name" type="string" maxOccurs="1" minOccurs="0"></element>
   				<element name="desc" type="string" maxOccurs="1" minOccurs="0"></element>
   				<element name="signature" type="string" maxOccurs="1" minOccurs="0"></element>
   				<element name="type" type="string" maxOccurs="1" minOccurs="0"></element>
   				<element name="bindToReturnValue" type="boolean" maxOccurs="1" minOccurs="0" default="false"></element>
   			</sequence>
   		</complexType>
   </element>


   <simpleType name="edgeType">
   	<restriction base="string">
   		<enumeration value="VisitFieldInsnEdge"></enumeration>
   		<enumeration value="VisitIincInsnEdge"></enumeration>
   		<enumeration value="VisitInsnEdge"></enumeration>
   		<enumeration value="VisitIntInsnEdge"></enumeration>
   		<enumeration value="VisitJumpInsnEdge"></enumeration>
   		<enumeration value="VisitLdcInsnEdge"></enumeration>
   		<enumeration value="VisitLocalVariableEdge"></enumeration>
   		<enumeration value="VisitMethodInsnEdge"></enumeration>
   		<enumeration value="VisitMultiANewArrayInsnEdge"></enumeration>
   		<enumeration value="VisitTableSwitchInsnEdge"></enumeration>
   		<enumeration value="VisitTryCatchBlockEdge"></enumeration>
   		<enumeration value="VisitTypeInsnEdge"></enumeration>
   		<enumeration value="VisitVarInsnEdge"></enumeration>
   	</restriction>
   </simpleType>

   
</schema>

=== ruizhang2015/codekp/ASMAnalysisFactory/detector_badUseOfReturnForReadLine.xml
<?xml version="1.0" encoding="UTF-8"?>
<Automachine  >
<!--   xmlns="http://mass.pku.edu.cn" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://mass.pku.edu.cn automachine.xsd" --> 
	<description>use IFNULL/IFNONNULL after calling readLine()</description>
	<errorMessage>use IFNULL/IFNONNULL after calling readLine()</errorMessage>
	<endMeanViolateDefect>true</endMeanViolateDefect>
	<objectSensitive>false</objectSensitive>
	<onlyConcernClass></onlyConcernClass>
	<allOpcodePushOjectAutomachine>false</allOpcodePushOjectAutomachine>	
	<severeLevel>0</severeLevel>
	<state>
		<number>1</number>
		<isEndState>false</isEndState>
		<isOriginState>true</isOriginState>
		<exceptionState>1</exceptionState>		
		<edge>
			<class>VisitMethodInsnEdge</class>
			<toState>2</toState>
			<opcode>INVOKEVIRTUAL</opcode>
			<owner>java/io/BufferedReader</owner>
			<name>readLine</name>
			<desc>()Ljava/lang/String;</desc>
		</edge>		
		<edge>
			<class>VisitMethodInsnEdge</class>
			<toState>2</toState>
			<opcode>INVOKEVIRTUAL</opcode>
			<owner>java/io/DataInputStream</owner>
			<name>readLine</name>
			<desc>()Ljava/lang/String;</desc>
		</edge>		
		<edge>
			<class>VisitMethodInsnEdge</class>
			<toState>2</toState>
			<opcode>INVOKEVIRTUAL</opcode>
			<owner>java/io/ObjectInputStream</owner>
			<name>readLine</name>
			<desc>()Ljava/lang/String;</desc>
		</edge>					
	</state>
	
	<state>
		<number>2</number>
		<isEndState>false</isEndState>
		<isOriginState>false</isOriginState>
		<exceptionState>1</exceptionState>	
		<edge>
			<class>VisitJumpInsnEdge</class>
			<toState>3</toState>
			<opcode>IFNULL</opcode>			
		</edge>
		<edge>
			<class>VisitJumpInsnEdge</class>
			<toState>3</toState>
			<opcode>IFNONNULL</opcode>		
		</edge>	
	</state>
	
	<state>
		<number>3</number>		
		<isEndState>true</isEndState>
		<isOriginState>false</isOriginState>
		<exceptionState>3</exceptionState>
	</state>	
</Automachine>

=== ruizhang2015/codekp/ASMAnalysisFactory/detector_nextDouble_d2i.xml
<?xml version="1.0" encoding="UTF-8"?>
<Automachine  >
<!--   xmlns="http://mass.pku.edu.cn" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://mass.pku.edu.cn automachine.xsd" --> 
	<description>Call Random.nextDouble()/Math.random(), then use d2i.</description>
	<errorMessage>Call Random.nextDouble()/Math.random(), then use d2i.</errorMessage>
	<endMeanViolateDefect>true</endMeanViolateDefect>
	<objectSensitive>false</objectSensitive>
	<onlyConcernClass></onlyConcernClass>
	<allOpcodePushOjectAutomachine>false</allOpcodePushOjectAutomachine>	
	<severeLevel>0</severeLevel>
	<state>
		<number>1</number>
		<isEndState>false</isEndState>
		<isOriginState>true</isOriginState>
		<exceptionState>1</exceptionState>		
		    <edge>
				<class>VisitMethodInsnEdge</class>
				<toState>2</toState>
				<opcode>INVOKEVIRTUAL</opcode>
				<owner>java/util/Random</owner>
				<name>nextDouble</name>
				<desc>()D</desc>
			</edge>
		
		    <edge>
				<class>VisitMethodInsnEdge</class>
				<toState>2</toState>
				<opcode>INVOKESTATIC</opcode>
				<owner>java/lang/Math</owner>
				<name>random</name>
				<desc>()D</desc>
			</edge>					
	</state>
	
	<state>
		<number>2</number>
		<isEndState>false</isEndState>
		<isOriginState>false</isOriginState>
		<exceptionState>1</exceptionState>
		
	  	    <edge>
				<class>VisitInsnEdge</class>
				<toState>3</toState>
				<opcode>d2i</opcode>				
			</edge>		
	</state>
	
	<state>
		<number>3</number>		
		<isEndState>true</isEndState>
		<isOriginState>false</isOriginState>
		<exceptionState>3</exceptionState>
	</state>	
</Automachine>

=== ruizhang2015/codekp/ASMAnalysisFactory/detector_i2d_ceilround.xml
<?xml version="1.0" encoding="UTF-8"?>
<Automachine  >
<!--   xmlns="http://mass.pku.edu.cn" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://mass.pku.edu.cn automachine.xsd" --> 
	<description>i2d then call Math.ceil() or Math.round()</description>
	<errorMessage>i2d then call Math.ceil() or Math.round()</errorMessage>
	<endMeanViolateDefect>true</endMeanViolateDefect>
	<objectSensitive>false</objectSensitive>
	<onlyConcernClass></onlyConcernClass>
	<allOpcodePushOjectAutomachine>false</allOpcodePushOjectAutomachine>	
	<severeLevel>0</severeLevel>
	<state>
		<number>1</number>
		<isEndState>false</isEndState>
		<isOriginState>true</isOriginState>
		<exceptionState>1</exceptionState>		
			<edge>
				<class>VisitInsnEdge</class>
				<toState>2</toState>
				<opcode>I2D</opcode>
				
			</edge>
			<edge>
				<class>VisitInsnEdge</class>
				<toState>2</toState>
				<opcode>fconst_1</opcode>
				
			</edge>
			<edge>
				<class>VisitInsnEdge</class>
				<toState>2</toState>
				<opcode>dconst_1</opcode>
				
			</edge>
			<edge>
				<class>VisitInsnEdge</class>
				<toState>2</toState>
				<opcode>ldc2_w</opcode>
				
			</edge>
		
	</state>
	
	<state>
		<number>2</number>
		<isEndState>false</isEndState>
		<isOriginState>false</isOriginState>
		<exceptionState>1</exceptionState>
		
			<edge>
				<class>VisitMethodInsnEdge</class>
				<toState>3</toState>
				<opcode>INVOKESTATIC</opcode>
				<owner>java/lang/Math</owner>
				<name>ceil</name>
				<desc>(D)D</desc>
			</edge>
			<edge>
				<class>VisitMethodInsnEdge</class>
				<toState>3</toState>
				<opcode>INVOKESTATIC</opcode>
				<owner>java/lang/Math</owner>
				<name>round</name>
				<desc>(F)I</desc>
			</edge>
			
		
		
	</state>
	
	<state>
		<number>3</number>		
		<isEndState>true</isEndState>
		<isOriginState>false</isOriginState>
		<exceptionState>3</exceptionState>
	</state>
	


</Automachine>

=== ruizhang2015/codekp/ASMAnalysisFactory/detector_nextDouble_duml_d2i.xml
<?xml version="1.0" encoding="UTF-8"?>
<Automachine  >
<!--   xmlns="http://mass.pku.edu.cn" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://mass.pku.edu.cn automachine.xsd" --> 
	<description>Get a random integer by calling Random.nextDouble()/Math.random() and multiply an integer with the result.</description>
	<errorMessage>Get a random integer by calling Random.nextDouble()/Math.random() and multiply an integer with the result.</errorMessage>
	<endMeanViolateDefect>true</endMeanViolateDefect>
	<objectSensitive>false</objectSensitive>
	<onlyConcernClass></onlyConcernClass>
	<allOpcodePushOjectAutomachine>false</allOpcodePushOjectAutomachine>	
	<severeLevel>0</severeLevel>
	<state>
		<number>1</number>
		<isEndState>false</isEndState>
		<isOriginState>true</isOriginState>
		<exceptionState>1</exceptionState>		
		    <edge>
				<class>VisitMethodInsnEdge</class>
				<toState>2</toState>
				<opcode>INVOKEVIRTUAL</opcode>
				<owner>java/util/Random</owner>
				<name>nextDouble</name>
				<desc>()D</desc>
			</edge>
		
		    <edge>
				<class>VisitMethodInsnEdge</class>
				<toState>2</toState>
				<opcode>INVOKESTATIC</opcode>
				<owner>java/lang/Math</owner>
				<name>random</name>
				<desc>()D</desc>
			</edge>					
	</state>
	
	<state>
		<number>2</number>
		<isEndState>false</isEndState>
		<isOriginState>false</isOriginState>
		<exceptionState>1</exceptionState>
		
	  	    <edge>
				<class>VisitInsnEdge</class>
				<toState>3</toState>
				<opcode>dmul</opcode>				
			</edge>		
	</state>
	
	
	<state>
		<number>3</number>
		<isEndState>false</isEndState>
		<isOriginState>false</isOriginState>
		<exceptionState>1</exceptionState>
		
	  	    <edge>
				<class>VisitInsnEdge</class>
				<toState>4</toState>
				<opcode>d2i</opcode>				
			</edge>		
	</state>
	
	<state>
		<number>4</number>		
		<isEndState>true</isEndState>
		<isOriginState>false</isOriginState>
		<exceptionState>4</exceptionState>
	</state>	
</Automachine>

=== ruizhang2015/codekp/ASMAnalysisFactory/detector_badUseOfReturnForIndexOf.xml
<?xml version="1.0" encoding="UTF-8"?>
<Automachine  >
<!--   xmlns="http://mass.pku.edu.cn" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://mass.pku.edu.cn automachine.xsd" --> 
	<description>use IFLE/IFGT after calling java.lang.String.indexOf()</description>
	<errorMessage>use IFLE/IFGT after calling java.lang.String.indexOf()</errorMessage>
	<endMeanViolateDefect>true</endMeanViolateDefect>
	<objectSensitive>false</objectSensitive>
	<onlyConcernClass></onlyConcernClass>
	<allOpcodePushOjectAutomachine>false</allOpcodePushOjectAutomachine>	
	<severeLevel>0</severeLevel>
	<state>
		<number>1</number>
		<isEndState>false</isEndState>
		<isOriginState>true</isOriginState>
		<exceptionState>1</exceptionState>		
		<edge>
			<class>VisitMethodInsnEdge</class>
			<toState>2</toState>
			<opcode>INVOKEVIRTUAL</opcode>
			<owner>java/lang/String</owner>
			<name>indexOf</name>
			<desc>(Ljava/lang/String;)I</desc>
		</edge>			
	</state>
	
	<state>
		<number>2</number>
		<isEndState>false</isEndState>
		<isOriginState>false</isOriginState>
		<exceptionState>1</exceptionState>	
		<edge>
			<class>VisitJumpInsnEdge</class>
			<toState>3</toState>
			<opcode>IFLE</opcode>			
		</edge>
		<edge>
			<class>VisitJumpInsnEdge</class>
			<toState>3</toState>
			<opcode>IFGT</opcode>		
		</edge>	
	</state>
	
	<state>
		<number>3</number>		
		<isEndState>true</isEndState>
		<isOriginState>false</isOriginState>
		<exceptionState>3</exceptionState>
	</state>	
</Automachine>
